defaults: &defaults
  uri: <%= ENV['mongodb://stingray:pennapps@ds037587-a.mongolab.com:37587/heroku_app7603312'] %>
  database: heroku_app7603312
  username: stingray
  password: pennapps

development:
  <<: *defaults
  host: ds037587-a.mongolab.com
  port: 37587

test:
  <<: *defaults

# set these environment variables on your prod server
production:
  <<: *defaults
  host: ds037587-a.mongolab.com
  port: 37587